### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by marcode95**
-reverse friendship added
-when a pending friendship is accepted two friendships are created

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @marcode95**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] in the users index page two things should happen:
-1 when a user1 sends an invitation to user2, user2 should see the invitation status (i.e. pending ) and be able to accept it on the users index page.
 2- when user1 is a friend with user2, the friendship status of friend should appear next to his name in the users index page.



---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by marcode95** [comment]
There seems to be a misunderstanding. Your issues reference the second milestone, which already got approved by another TSE. This pull request is for the third milestone about implementing a normal&reverse friendship. I mentioned that in the review request form too.

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @marcode95**

 
---

These are not implementation changes, I'm simply requesting to add the functionality that you already created to the users index page. that's it.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by marcode95** [comment]
Hey there! Let me explain again:
Your issue is referencing the second milestone about implementing friend request functionalities. It has already been approved - you can check my other pull requests just to be sure. Also your suggested changes aren‘t part of the microverse requirements, which is why most other TSE’s who already reviewed (and approved) my code didn’t request them either. This pull request is for the „Friendships v2“ milestone that is dealing with the reverse friendship functionality, so I‘d like to get a TSE‘s opinion on that. I know you only have limited time to deal with each project and especially in rails things can get quite complicated, so if you have any questions don‘t hesitate to contact me on slack.

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work on this PR. You did well implementing the features required.
Let's work on some crucial changes before we can merge this PR.
- [ ] The friendship model does not quite work as expected. When I send a friend request to a user, they can confirm (both from the UI and the console) the request as expected but they don't appear as a friend in my list of friends and I also don't appear as a friend in their list of friends. This is not supposed to be happening.
- [ ] You currently do not have a method defined in your User model for sending friend requests to other user. I was able to send requests from the UI. Add a method to the model for easy testing of this logic from the `rails console`. **This is not required but would make life easy for you and the TSE's**


### Martin Afani

**Comment by marcode95** [comment]
Hey there!
I just tried out the friend's list thing and it's working for me - did you mean this? 
ror-friends

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @marcode95 and @whiz25  ! 
### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

**Recommended**

- [ ] As stated by the previous TSEs, when user1 is a friend with user2, the friendship status of "friend" should appear next to his name on the users' index page. [OPTIONAL]
- [ ] Also, this is optional, but instead of just having texts as the accept or decline options, make them buttons, that makes it easier for users. [OPTIONAL]

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @marcode95  & @whiz25**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
